### ISSUE TITLE
Flexible Logging

### ISSUE THREAD

**Issue by buttercat1791** [mleku/realy#1]
It appears that realy only logs to stdout/stderr currently.  Some users will likely want to be able to configure different log streams.

The `Config` struct used in setup allows users to set [log levels for the program and for the DB](https://github.com/mleku/realy/blob/4a3d7c0a2243dfab87fe6a05a987406c82b90926/cmd/realy/app/config.go#L26-L27), but not the log destination.

The `lol` library used for logging in this project supports variable log destinations out of the box.  As seen in `log.go`, it may be [passed a writer during setup](https://github.com/mleku/realy/blob/4a3d7c0a2243dfab87fe6a05a987406c82b90926/lol/log.go#L294), and [that writer may be anything, not just stdout](https://github.com/mleku/realy/blob/4a3d7c0a2243dfab87fe6a05a987406c82b90926/lol/log.go#L83-L85).

If only console logging is currently configurable, making alternate logging methods available on configuration would be a worthwhile addition.

**Comment by mleku** [comment]
closing
